version: 2
defaults: &defaults
  docker:
    - image: tapsellorg/android-sdk:v4.1.1

jobs:

  build:
    <<: *defaults

    steps:
      - checkout
      - run:
            name: Build APK
            command: gradle assembleDebug

workflows:
  version: 2

  build:
    jobs:
      - build
